package com.example.studyvault.exception;

public enum ErrorCode {
    VALIDATION_ERROR, UNAUTHORIZED, FORBIDDEN, NOTE_NOT_FOUND, TAG_NOT_FOUND,
    EMAIL_ALREADY_EXISTS, USERNAME_ALREADY_EXISTS, TAG_ALREADY_EXISTS, NOTE_TAG_ALREADY_EXISTS,
    MALFORMED_REQUEST, INVALID_REQUEST, INVALID_MARKDOWN_FILE, FILE_TOO_LARGE,
    TASK_NOT_FOUND, INVALID_TASK_STATUS, INVALID_REVIEW_STATUS,
    AI_TIMEOUT, AI_NOT_CONFIGURED, AI_RATE_LIMITED, AI_PROVIDER_ERROR, INTERNAL_SERVER_ERROR
}
