const seedNotes=[
 {id:1,title:'PostgreSQL 索引与查询优化',excerpt:'索引不是越多越好。理解 B-Tree、覆盖索引和 EXPLAIN，才能让查询真正跑得快。',tag:'数据库',tags:['数据库','后端'],updated:'今天 10:42',favorite:true,content:'## 为什么需要索引？\n\n索引是帮助数据库快速定位数据的数据结构。最常见的 **B-Tree** 索引适合等值查询和范围查询。\n\n### 一、先看执行计划\n\n使用 `EXPLAIN ANALYZE` 观察真实执行路径，重点关注 Seq Scan、Index Scan 和实际耗时。\n\n- 选择性高的字段更适合建索引\n- 避免在低基数字段上盲目加索引\n- 写入频繁的表要评估维护成本\n\n> 好的索引，是让数据库少做无用功，而不是让索引数量变多。'},
 {id:2,title:'Spring Security 登录流程梳理',excerpt:'从请求进入 FilterChain，到 Authentication 写入 SecurityContext 的完整链路。',tag:'后端',tags:['后端','Java'],updated:'昨天 21:18',favorite:true,content:'## FilterChain 到底做了什么？\n\nSpring Security 将认证与授权拆成多个过滤器，每个过滤器只关注一个职责。'},
 {id:3,title:'操作系统：进程与线程',excerpt:'进程是资源分配的基本单位，线程是 CPU 调度的基本单位。',tag:'操作系统',tags:['操作系统'],updated:'8月 28日',favorite:false,content:'## 进程与线程\n\n进程拥有独立的地址空间，线程共享进程资源。'},
 {id:4,title:'Docker Compose 部署清单',excerpt:'记录 StudyVault 从本地到云服务器的部署步骤和常用命令。',tag:'部署',tags:['部署','Docker'],updated:'8月 26日',favorite:true,content:'## 部署前检查\n\n确认环境变量、镜像构建和数据卷配置。'},
 {id:5,title:'HTTP 缓存策略',excerpt:'Cache-Control、ETag 与浏览器缓存的实践笔记。',tag:'前端',tags:['前端'],updated:'8月 23日',favorite:false,content:'## 强缓存与协商缓存\n\n合理的缓存策略可以显著降低请求次数。'},
 {id:6,title:'我的学习方法复盘',excerpt:'把大目标拆成一周一个可交付结果，保持稳定的反馈循环。',tag:'方法论',tags:['方法论'],updated:'8月 20日',favorite:false,content:'## 每周复盘\n\n记录做得好的地方、卡住的地方，以及下周的一个重点。'}
];
let notes=JSON.parse(localStorage.getItem('studyvault-notes')||'null')||seedNotes; let currentView='overview'; let selectedId=1; let filter='全部';
const $=s=>document.querySelector(s); const save=()=>localStorage.setItem('studyvault-notes',JSON.stringify(notes));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function renderTags(){const tags=[['数据库',4],['后端',3],['前端',2],['方法论',2]];$('#tagList').innerHTML=tags.map(t=>`<div class="tag-item" data-tag="${t[0]}"><span class="tag-dot"></span>${t[0]}<em>${t[1]}</em></div>`).join('');document.querySelectorAll('.tag-item').forEach(e=>e.onclick=()=>{filter=e.dataset.tag;currentView='notes';render()})}
function layout(){document.querySelectorAll('.nav-item[data-view]').forEach(e=>e.classList.toggle('active',e.dataset.view===currentView));const titles={overview:'总览',notes:'全部笔记',favorites:'我的收藏',trash:'回收站',settings:'设置'};$('#pageTitle').textContent=titles[currentView]||'总览'}
function render(){layout();renderTags();const content=$('#pageContent'); if(currentView==='overview') content.innerHTML=overview(); else if(currentView==='notes'||currentView==='favorites'||currentView==='trash') content.innerHTML=notesView(); else content.innerHTML=settingsView(); bind();}
function overview(){return `<div class="hero"><div><div class="eyebrow">Study / 2024 秋季学期</div><h1>早上好，林同学 <span style="font-size:24px">✦</span></h1><p>把今天的思考，变成明天的能力。</p></div><div class="date-pill">⌁  2024年9月  ·  第 4 周</div></div><div class="stats-grid"><div class="stat-card"><div class="stat-head">笔记总数 <span class="stat-icon">▤</span></div><div class="stat-number">12</div><div class="stat-foot"><span class="trend">↑ 3</span> 比上周新增</div></div><div class="stat-card"><div class="stat-head">已收藏 <span class="stat-icon">☆</span></div><div class="stat-number">4</div><div class="stat-foot">保持你的灵感</div></div><div class="stat-card"><div class="stat-head">标签 <span class="stat-icon">#</span></div><div class="stat-number">8</div><div class="stat-foot">覆盖 4 个主题</div></div><div class="stat-card"><div class="stat-head">本周专注 <span class="stat-icon">◷</span></div><div class="stat-number">6.5 <small style="font-size:13px;font-weight:600">h</small></div><div class="stat-foot"><span class="trend">↑ 18%</span> 学习时长</div></div></div><div class="dashboard-grid"><section class="panel"><div class="panel-head"><h2>最近编辑</h2><button class="link-btn" data-go="notes">查看全部 →</button></div><div class="recent-list">${notes.slice(0,4).map(n=>`<div class="recent-row" data-note="${n.id}"><div class="file-icon">MD</div><div class="row-main"><div class="row-title">${n.title}</div><div class="row-meta">${n.excerpt}</div></div><span class="row-tag">${n.tag}</span><span class="row-time">${n.updated}</span></div>`).join('')}</div></section><section class="panel"><div class="panel-head"><h2>学习活动</h2><span class="sub">最近 7 天</span></div><div class="activity"><div class="activity-chart">${[35,52,40,76,55,92,67].map((h,i)=>`<div class="bar-col"><div class="bar ${i===5?'active':''}" style="height:${h}%"></div><div class="bar-label">${['一','二','三','四','五','六','日'][i]}</div></div>`).join('')}</div><div class="chart-note"><span>本周编辑笔记</span><strong>8 篇</strong></div></div></section></div>`}
function notesView(){let list=notes.filter(n=>currentView==='favorites'?n.favorite:currentView==='trash'?n.trashed:!n.trashed); if(filter!=='全部') list=list.filter(n=>n.tags.includes(filter)); const q=window.searchQ||''; if(q) list=list.filter(n=>(n.title+n.excerpt+n.content).toLowerCase().includes(q.toLowerCase())); const selected=list.find(n=>n.id===selectedId)||list[0]; if(selected) selectedId=selected.id; return `<div class="hero" style="margin-bottom:23px"><div><div class="eyebrow">Library</div><h1>${currentView==='trash'?'回收站':currentView==='favorites'?'我的收藏':'全部笔记'}</h1><p>${currentView==='trash'?'已删除的笔记会保留 30 天。':currentView==='favorites'?'收藏那些值得反复回看的内容。':'在你的知识库中，持续积累可复用的思考。'}</p></div><button class="new-note" id="newNoteBtn2" style="margin:0;height:38px;padding:0 15px">＋ 新建笔记</button></div><div class="notes-toolbar"><div class="search-box"><span>⌕</span><input id="searchInput" placeholder="搜索标题、正文..." value="${q}" /></div><div class="filter-group"><button class="filter-btn ${filter==='全部'?'active':''}" data-filter="全部">全部</button><button class="filter-btn ${filter==='后端'?'active':''}" data-filter="后端">后端</button><button class="filter-btn ${filter==='数据库'?'active':''}" data-filter="数据库">数据库</button><button class="filter-btn" id="sortBtn">最近编辑⌄</button></div></div><div class="notes-layout"><section class="notes-panel"><div class="note-list-head"><span>${list.length} 篇笔记</span><span>按最近编辑</span></div><div class="note-list">${list.length?list.map(n=>`<div class="note-card ${selected&&n.id===selected.id?'selected':''}" data-select="${n.id}"><div class="note-card-top"><h3>${n.title}</h3><button class="star ${n.favorite?'on':''}" data-fav="${n.id}">${n.favorite?'★':'☆'}</button></div><p>${n.excerpt}</p><div class="note-card-foot"><span class="row-tag">${n.tag}</span><span>·</span><span>${n.updated}</span></div></div>`).join(''):'<div class="view-empty"><div class="empty-icon">⌁</div><h2>还没有匹配的笔记</h2><p>换个关键词试试看，或新建一篇笔记。</p></div>'}</div></section>${selected?detail(selected):'<section class="note-detail"><div class="view-empty"><div class="empty-icon">▤</div><h2>选择一篇笔记</h2></div></section>'}</div>`}
function detail(n){return `<article class="note-detail"><div class="detail-top"><div><h1>${n.title}</h1><div class="detail-meta"><span>最后编辑于 ${n.updated}</span><span>·</span><span>约 3 分钟阅读</span></div></div><div class="detail-actions"><button class="small-btn" id="aiBtn">✦ AI 助手</button><button class="small-btn" id="editBtn">编辑</button><button class="small-btn" id="trashBtn">${n.trashed?'恢复':'移入回收站'}</button></div></div><div class="detail-tags">${n.tags.map(t=>`<span class="tag-chip"># ${t}</span>`).join('')}</div><div class="markdown-body">${md(n.content)}</div><div class="editor-footer"><span>Markdown · 自动保存</span><span>⌘ S 保存</span></div></article>`}
function md(s){return s.split('\n').map(l=>l.startsWith('## ')?`<h2>${l.slice(3)}</h2>`:l.startsWith('### ')?`<h3>${l.slice(4)}</h3>`:l.startsWith('- ')?`<li>${l.slice(2)}</li>`:l.startsWith('> ')?`<div class="callout">${l.slice(2)}</div>`:l?`<p>${l.replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/`(.*?)`/g,'<code>$1</code>')}</p>`:'').join('').replace(/(<li>.*?<\/li>)+/g,m=>`<ul>${m}</ul>`)}
function settingsView(){return `<div class="hero" style="margin-bottom:23px"><div><div class="eyebrow">Workspace</div><h1>设置</h1><p>管理你的空间偏好与数据。</p></div></div><div class="settings-grid"><div class="settings-menu"><button class="active">个人资料</button><button>外观偏好</button><button>数据与导出</button><button>关于 StudyVault</button></div><div class="settings-card"><h2>个人资料</h2><p>这些信息只会用于你的 StudyVault 空间。</p><div class="setting-row"><div>用户名 <span>林同学</span></div><button class="small-btn">编辑</button></div><div class="setting-row"><div>邮箱 <span>lin@example.com</span></div><button class="small-btn">修改</button></div><div class="setting-row"><div>自动保存 <span>编辑后实时保存草稿</span></div><div class="switch"><i></i></div></div></div></div>`}
function bind(){document.querySelectorAll('.nav-item[data-view]').forEach(e=>e.onclick=()=>{currentView=e.dataset.view;filter='全部';render()});document.querySelectorAll('[data-go]').forEach(e=>e.onclick=()=>{currentView=e.dataset.go;render()});document.querySelectorAll('[data-note]').forEach(e=>e.onclick=()=>{selectedId=+e.dataset.note;currentView='notes';render()});document.querySelectorAll('[data-select]').forEach(e=>e.onclick=()=>{selectedId=+e.dataset.select;render()});document.querySelectorAll('[data-fav]').forEach(e=>e.onclick=ev=>{ev.stopPropagation();const n=notes.find(x=>x.id===+e.dataset.fav);n.favorite=!n.favorite;save();render();toast(n.favorite?'已加入收藏':'已取消收藏')});document.querySelectorAll('[data-filter]').forEach(e=>e.onclick=()=>{filter=e.dataset.filter;render()});const si=$('#searchInput');if(si){si.oninput=()=>{window.searchQ=si.value;render()};si.focus();si.setSelectionRange(si.value.length,si.value.length)}const nb=$('#newNoteBtn2');if(nb)nb.onclick=newNote;const ai=$('#aiBtn');if(ai)ai.onclick=()=>{toast('AI 摘要已生成，已作为草稿添加到笔记底部')};const ed=$('#editBtn');if(ed)ed.onclick=()=>toast('编辑器将在下一步接入');const tr=$('#trashBtn');if(tr)tr.onclick=()=>{const n=notes.find(x=>x.id===selectedId);n.trashed=!n.trashed;save();toast(n.trashed?'已移入回收站':'笔记已恢复');render()}}
function newNote(){const id=Date.now();notes.unshift({id,title:'未命名笔记',excerpt:'开始记录你的新想法...',tag:'未分类',tags:['未分类'],updated:'刚刚',favorite:false,content:'## 开始写作\n\n记录下此刻的想法吧。'});selectedId=id;currentView='notes';save();render();toast('已创建新笔记')}
$('#newNoteBtn').onclick=newNote;$('#shortcutBtn').onclick=()=>toast('快捷键：N 新建笔记 · ⌘K 搜索 · ⌘S 保存');$('#addTagBtn').onclick=()=>{openModal('新建标签',`<label>标签名称</label><input id="tagInput" placeholder="例如：算法"/><div class="modal-actions"><button class="small-btn" id="cancelModal">取消</button><button class="small-btn primary" id="saveTag">创建标签</button></div>`);$('#saveTag').onclick=()=>{const v=$('#tagInput').value.trim();if(v){toast(`标签「${v}」已创建`);closeModal()}}};function openModal(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').classList.add('show');$('#tagInput')?.focus()}function closeModal(){$('#modal').classList.remove('show')}$('#closeModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};render();
